//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintManagementApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Complaint_tbl
    {
        public int ComplaintId { get; set; }

        [Required]
        [Display(Name ="Title")]
        public string Complaint_Title { get; set; }

        [Required]
        public string Discription { get; set; }

        [Required]
        public System.DateTime Date { get; set; }

        [Required]
        public string Status { get; set; }


        [Display(Name = "Updated On")]
        public Nullable<System.DateTime> UpdateOn { get; set; }
    }
}
